services:
  db:
    image: postgres:16
    container_name: thesis_db
    environment:
      POSTGRES_DB: thesis_db
      POSTGRES_USER: thesis_user
      POSTGRES_PASSWORD: thesis_password
    ports:
      - "5432:5432"
    volumes:
      - ./server/sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./server/sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
      - ./server/public/data:/docker-entrypoint-initdb.d/data
  
volumes:
  postgres_data: